import type { Metadata } from "next";
import { Inter, Syne } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from 'next-themes'
import { ThemeToggle } from '@/components/theme-toggle';



const displayFont = Syne({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-display',
});

const baseFont = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-default',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <ThemeToggle isDropDown={true} />
        </ThemeProvider>
      </body>
    </html>
  )
}